# Generated by Django 2.1 on 2018-12-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bolg_type',
            new_name='blog_type',
        ),
    ]
